ABSTRACT_SEM_ROLE = 0
ORDINARY_SEM_ROLE = 1
CAUSATIVE_SEM_ROLE = 2
DATIVE_SEM_ROLE = 3
JOB_SEM_ROLE = 4
ATE_SEM_ROLE = 5
SUPP_SEM_ROLE = 6
METTERE_PREP_SEM_ROLE = 7
AMBIGUOUS_SEM_ROLE = 8


F3_VALUES = [
    "ACTIVE",
    "ACTIVE_SI",
    "ACTIVE_SE_NE",
    "ACTIVE_CI_SI",
    "PASSIVE",
]

ACTV = F3_VALUES[0]
ACTV_S = F3_VALUES[1]
ACTV_SN = F3_VALUES[2]
ACTV_CI = F3_VALUES[3]
PASSV = F3_VALUES[4]
